@startuml
class User {
  - userID: int
  - username: string
  - hashedPassword: string
}

class Consultant {
  - consultantId: int
  - name: string
  - experienceInYears: int
  - hourlySalaryRequirementSek: int
}

class WorkProfile {
  - consultant: Consultant
  - workingLocations: Location[]
  - currentAssignments: Assignment[]
}

class Assignment {
  - assignmentID: int
  - location: Location
  - shift: string
  - hourlySalarySek: int
}

class Location {
  - locationID: int
  - name: string
  - lon: double
  - lat: double
  - municipality: string
}
@enduml